### ISSUE TITLE
I saw alot but this project is something else

### ISSUE THREAD

**Issue by Not-Zero-Blank** [nikkilocke/NextcloudApi#12]
This is the Worst library i saw in my Life. 
How are you going to use it? Fill out every field in Settings?
Whats so hard about to just make one Static method to setup the API like you want to, new API(string username, string password, Uri Server, string token = null)
This lib is the Worst i saw, even Script kiddies make it better

**Comment by nikkilocke** [comment]
There are two choices - create a settings file with all the necessary information in it, or have to pass all that information in the constructor call. I deliberately chose a settings file because it suited my purpose (I need to construct instances in many places in my code).

If you don't like that, you can always have a method to create a settings object then call the constructor and return the result.

And, if you don't like the library I wrote, and put on github so you can use it if you want, then don't use it, write a different one - you have the same access to the  Nextcloud Api docs as I did. 

Insulting someone who has offered you the benefit of their work, free of charge, is just rude.
